### ISSUE TITLE
feature request: WebKitGTK bindings

### ISSUE THREAD

**Issue by medovina** [StefanSalewski/gintro#106]
Thanks for the great work on gintro!

[WebKitGTK](https://webkitgtk.org/)  is commonly used in the GNOME/GTK world for writing applications that display or interact with HTML.  It would be very nice to have gintro bindings available for it.

**Comment by StefanSalewski** [comment]
I have learned in the last years to be a bit carefully with the addition of more packages to gintro. I had added gstreamer because someone requested it, but that one vanished and never returned. Someone other requested vte and also vanished fast. (Well for vte we have a different active user from France now at least.) Lately there was a serious request for libnice, which I fulfilled. But as I had no experience with libnice and libnice is a low level package, it took me more than 50 hours to provide a working demo example.

For WebKitGTK: I would expect it to be a really large library, which can generate much trouble. And the question is who would use it for what? Do you intent to write a Firefox clone in Nim? Have you experience with use of WebKitGTK from other programming languages so that you can help providing examples? I unfortunately have no experience with that. Unfortunately each new package increases the maintaining costs.

Well your real name seems to sound familiar, are you one of the authors of

https://researcher.watson.ibm.com/researcher/files/us-bacon/Dingle07Ownership.pdf

**Comment by medovina** [comment]
Hi Stefan,

I am, indeed, a co-author of that paper with David Bacon.  It was never actually published, so I'm quite surprised that you are aware of it!  :)

You're right that WebKitGTK is a large library.

I'm currently working on a WYSIWYG HTML editor for the GNOME desktop.  The goal is to for it to look and feel like a simple word processor, so it should be useful not only for editing HTML pages that you want to publish online, but even as a lightweight alternative to LibreOffice for editing rich text documents for any purpose, one that just happens to use HTML as its document storage format.  Using WebKitGTK for rendering the document is the obvious choice.

At the moment I'm using Python, but it would be interesting to write it in Nim if possible.  Hence my feature request.

More generally, I'd love to see all the GNOME apps port away from C toward some other language over time, since C is just too low-level and hard to read and write.  I think Nim is probably the best candidate we currently have for such a language.  So in the long term I think it would be great if all the important core libraries are available in Nim.  I'm glad you added GStreamer, for example.  And WebKitGTK is another such library.  Of course, that's a long-term goal and you can't be expected to do all the work yourself, and I hope other contributors will join the effort.

As to whether you want to attempt to add WebKitGTK, it's up to you.  My hope is that the existing gobject-introspection bindings for WebKitGTK will work with your Nim framework without too much effort, but I know that's a lot to hope for.  If you do want to add this, I'd be happy to attempt to port my editor to Nim which should be a significant example.

**Comment by StefanSalewski** [comment]
>a co-author of that paper with David Bacon.

Really interesting. The Bacon/Dingle papers where discussed in the Nim community maybe two years ago, and I think they have indeed influenced the current ARC/ORC deterministic memory management system. I am really happy that we have ARC now, I was not too happy with the old delayed refc GC.

Your arguments for WebKitGTK sound good, so I will see what I can do about it. In the optimal case it requires only adding one line to the generator script, but in reallity it can be more work. For gstreamer the problem was that gstreamer authors are not members of the gtk/gnome core team, so there where serious differences in the gobject-introspection stuff, I had to ask for support by the GTK core devs, which basically is only Mr. Bassi currently. And for libnice the problem was that that lib is really a low level lib, and that the user intended to use it with Windows 8.1 while I am using Linux only.

For the GTK/GNOME C relation: You may know that the Vala project is generally regarded as failed and death now. I think that some of the GTK core devs, at least Mr Bassi know well the problems of C. The Rust team around Mr Droege has put a large effort to support GTK and maybe partly replace C for GTK with Rust language. Indeed in the last years we got a few new GTK tools written in Rust. So I would strongly assume that Rust is a much better candidate for replacing C in GTK than Nim. Rust is supported by the Mozilla foundation, which had a finance budget of a few 100 Million $ a year in the last years.

For the gintro Nim bindings: I am working on it since more than 4 years now, with a time budget of about 400 hours a year. And before that, in 2015 I created the oldgtk3 low level bindings. It is indeed much effort regarding the small number of Nim GTK users which we currently have. And it is a fact that many people just don't like GTK, including Mr Rumpf himself, so we can not hope for much support from him or the Nim team for the gintro package. 

In last summer I started writing the GTK4 book, as some people told me that it is too difficult to learn GTK from the C API alone. But unfortunately that books is only 20% complete yet.

Well I will look at the WebKitGTK stuff, maybe next weekend.

**Comment by medovina** [comment]
That's fascinating that the Nim community discussed my/David's paper on memory management!  I had no idea that had happened.  If it had an influence on your deterministic memory management system, all the better!

I agree that Vala is pretty much on the way out.  It's a little sad for me to see that, since I have a past with Vala.  I was the founder of Yorba, an open source development group that built a few applications in Vala including the Geary mail client which has remained fairly popular.  But I think it's pretty clear that Rust and Nim have much more momentum today.

I don't have much experience with either Rust or Nim, but I have to say that my first impression of Nim is more positive.  Really it would be a valuable exercise for me to attempt to port my editor to both Rust and Nim to see how the experiences compare.

It's impressive that you are so devoted to gintro and have put so much time and energy into it.  It's a shame that Mr. Rumpf is not a GTK fan, but hopefully with your work Nim will still be a strong choice for GTK applications in the future.

I agree that GTK is too difficult to learn from the C API alone.  In my opinion the best resource for learning GTK today is the book "Foundations of PyGTK Development" by W. David Ashley and Andrew Krause, though even that recent book is becoming a bit dated in some ways.

I'm hopeful that the introspection bindings for WebKitGTK will work without much effort in Nim since they seem to work well in Python, which can also import WebKitGTK using gobject-introspection.  However, probably the only way to find out is to add that one line to the generator script and see what happens.  :)

**Comment by StefanSalewski** [comment]
>best resource for learning GTK today is the book "Foundations of PyGTK Development" by W. David Ashley and Andrew Krause

I read the book of Andrew Krause in 2007. Was OK and helped me learning GTK2. But from the content it was only a 250 pages book, which he bloated to 500 pages with a lot of redundant stuff.

The Python successor seems to be not very popular, has never been mentioned on GTK mailing list or GTK forum. Often such "refreshed" releases are disappointing.

So I fear the best GTK4 book is still my one -- unfortunately it is only 20% complete:

http://ssalewski.de/gtkprogramming.html

I have just released gintro v0.8.5 with webkit support. Only GTK3 still, I tried to built it for GTK4 but it failed, we have to wait a few weeks for the next webkit release for GTK4.

I have created one simple GTK3 example:

https://github.com/StefanSalewski/gintro/blob/master/examples/gtk3/webkitgtk.nim

**Comment by medovina** [comment]
Stefan, thanks for the quick turnaround!  I guess maybe this wasn't so tough after all.  :)  I'll try to take a look at your new release in the next day or two.

**Comment by medovina** [comment]
Stefan, I'm sorry to be another one of your commenters who asked for bindings, and then vanished!  But the truth is that I took a deeper look at Nim, and ultimately decided to use Python for my project instead, at least for now.  Nim is just a lower-level language than I want.  A key difference is that assignment in Nim means **copying**, like in C and C++.  I definitely want a language where assignment instead means making another reference to the same object, like in C#, Java, and Python.  My application isn't performance-critical, and I want to think as little as possible about memory allocation, at least in the beginning stages.  Perhaps at some later point I'll port to a lower-level language, and if that happens Nim would be a candidate.

Anyway, so I think we can close this since you've implemented it and I don't expect to actually use these bindings any time soon.  If it took a significant amount of your time to create them, then my apologies - probably I should have done more experimentation with Nim before making my request.  In any case, best of luck with all your ongoing Nim work.

**Comment by StefanSalewski** [comment]
Sad to hear that you will not continue (or even start) using Nim.

>A key difference is that assignment in Nim means copying,

Well, in Nim we have and use ref types, which are managed pointers. When we copy or assign for ref types, we copy the ref, not the object itself. That should be exactly what you want.

Why I just opened this issue again: I have just added webkitgtk support for GTK4. WebkitGtk lib works for GTK4 with latest tarball WebKitGTK 2.31.1 finally. Do worry too much about my work spent for providing webkitgtk bindings, it was only a dozen hours totally, and I am sure sooner or later someone other has asked for it, again without really using it :-)
