### ISSUE TITLE
"connect" returns a value

### ISSUE THREAD

**Issue by lscrd** [StefanSalewski/gintro#11]
This is not an issue, but a remark.

"connect" is a macro which returns a value, not different, I think, of the values returned by the miscellaneous connect functions of GTK.

But, for some reason, the compiler doesn’t check that the value returned by "connect" is assigned or discarded. This may, in some cases, cause errors difficult to find (and bugs if, unfortunately, the types match which is unlikely as "connect" returns as "culong").

Here is an example:

```Nim
proc p(): SomeType =
  result = someValue
  # Body of the procedure.
  # ...
  # ...
  # The following line is the last line of the function, so the value returned by "connect"
  # is used as return value for the procedure.
  connect(someObject, "signal", someHandler)
```

Not sure we can do something to avoid this and it is not a frequent case, but I encountered it.

**Comment by StefanSalewski** [comment]
That is an interesting remark indeed.

The Nim connect macro/template is marked with the {.discardable.} pragma by intend so that the user is not forced to write "discard connect(...)". Same as in C code. connect() can return an clong ID, which may be needed in rare cases, but generally is not needed. (The chess board uses that ID to block the handler when computer is thinking for example). But that issue would still exist without the discardable pragma when connect is the last statement in an proc that returns an culong. Well, maybe the compiler would warn for that case. So this is more an issue for the Nim bug tracker or the Nim forum.

**Comment by StefanSalewski** [comment]
I have tried to provide a test case, but it seems to work fine with V 0.17.2

```nim

import macros

macro mymacro(i: int): untyped =

  let x = """
proc rint(i: int): int {.discardable.} =
  7
rint(64)
"""
  result = parseStmt(x)

template myTemp(i: int): untyped =
  mymacro(i)

proc rint2(i: int): int =
  result = 13
  myTemp(0)

echo rint2(0)
```

Output is 13 as expected. So there must be something very special to my connect() macro?

**Comment by StefanSalewski** [comment]
Can not reproduce with latest Nim v 0.17.2

This code always outputs 13 as expected for me.

```nim
# nim c button.nim
import gintro/[gtk, glib, gobject, gio]

proc buttonClicked (button: Button) =
  button.label = utf8Strreverse(button.label, -1)

proc p1(b: Button): culong =
  result = 13
  #b.connect("clicked",  buttonClicked)
  connect(b, "clicked",  buttonClicked)

proc activate (app: Application) =
  let window = newApplicationWindow(app)
  window.title = "GNOME Button"
  window.defaultSize = (250, 50)
  let button = newButton("Click Me")
  window.add(button)
  #button.connect("clicked",  buttonClicked)
  echo p1(button)
  window.showAll

proc main =
  let app = newApplication("org.gtk.example")
  connect(app, "activate", activate)
  discard app.run

main()
```

**Comment by StefanSalewski** [comment]
Closing as I can not reproduce the issue with latest Nim v0.17.2.

Please reopen if you can give an example with issue for latest Nim compiler.
