### ISSUE TITLE
gio.nim codegen broken (new GTK3 version)

### ISSUE THREAD

**Issue by Dankr4d** [StefanSalewski/gintro#179]
Hi,
after a GTK3 update (using arch linux or msys2) the gio code is broken.

Installed GTK3 version: `extra/gtk3 1:3.24.30+62+g8d04980f38-2 [installed]`

Exception:
```bash
/home/dankrad/.nimble/pkgs/gintro-0.9.4/gintro/gio.nim(25396, 6) Error: overloaded 'dupDefault' leads to ambiguous calls
```

In `gio.nim`, there are now overloaded functions, by return type:
```nim
proc dupDefault*(): MemoryMonitor

proc dupDefault*(): PowerProfileMonitor
```

**Comment by Dankr4d** [comment]
I downgraded gintro and also python-gobject, but it still generates those two functions.

**Comment by StefanSalewski** [comment]
Thanks for reporting. Yes, that can happen, it's in some way a result of the name mangling and the fact that the return type of a function for Nim is not considered for overload resolution.

But it's a result of your GTK3 update, so downgrading gintro can not help. I am a bit surprised that this happened for GTK3, which is regarded as stable now. I hope that I can reproduce it on my Linux box. The fix is usually to rename the functions manually.

If you have a grep command available, then please execute in a terminal window

```
grep -C12 "proc dupDefault" ~/.nimble/pkgs/gintro-#v0.9.2/gintro/gio.nim
```

for your actual gintro version installed, so that I can see the original function names. For my Linux box there is currently only g_memory_monitor_dup_default(), but you should have one more.

I was going to release v0.9.5 soon, which contains a fix for very old GTK3 versions like Debian Buster, we can add a fix for your problem then too.

**Comment by Dankr4d** [comment]
Sorry, I accidentally wrote gintro, but meant gtk.

Your requested grep execution (with `-C` num set to 16, to show the whole function implementation): 
```
[dankrad@TNB ~]$ grep -C16 "proc dupDefault" ~/.nimble/pkgs/gintro-0.9.4/gintro/gio.nim 
type
  MemoryMonitorWarningLevel* {.size: sizeof(cint), pure.} = enum
    low = 50
    medium = 100
    critical = 255

type
  MemoryMonitor00* = object of gobject.Object00
  MemoryMonitor* = ref object of gobject.Object

proc scLowMemoryWarning*(self: MemoryMonitor;  p: proc (self: ptr MemoryMonitor00; level: MemoryMonitorWarningLevel; xdata: pointer) {.cdecl.}, xdata: pointer, cf: gobject.ConnectFlags): culong =
  g_signal_connect_data(self.impl, "low-memory-warning", cast[GCallback](p), xdata, nil, cf)

proc g_memory_monitor_dup_default(): ptr MemoryMonitor00 {.
    importc, libprag.}

proc dupDefault*(): MemoryMonitor =
  let gobj = g_memory_monitor_dup_default()
  let qdata = g_object_get_qdata(gobj, Quark)
  if qdata != nil:
    result = cast[type(result)](qdata)
    assert(result.impl == gobj)
  else:
    fnew(result, gio.finalizeGObject)
    result.impl = gobj
    GC_ref(result)
    if g_object_is_floating(result.impl).int != 0:
      discard g_object_ref_sink(result.impl)
    g_object_add_toggle_ref(result.impl, toggleNotify, addr(result[]))
    g_object_unref(result.impl)
    assert(g_object_get_qdata(result.impl, Quark) == nil)
    g_object_set_qdata(result.impl, Quark, addr(result[]))

--
  if gerror != nil:
    let msg = $gerror.message
    g_error_free(gerror[])
    raise newException(GException, msg)
  result = resul0

type
  PollableSourceFunc* = proc (pollableStream: ptr gobject.Object00; userData: pointer): gboolean {.cdecl.}

type
  PowerProfileMonitor00* = object of gobject.Object00
  PowerProfileMonitor* = ref object of gobject.Object

proc g_power_profile_monitor_dup_default(): ptr PowerProfileMonitor00 {.
    importc, libprag.}

proc dupDefault*(): PowerProfileMonitor =
  let gobj = g_power_profile_monitor_dup_default()
  let qdata = g_object_get_qdata(gobj, Quark)
  if qdata != nil:
    result = cast[type(result)](qdata)
    assert(result.impl == gobj)
  else:
    fnew(result, gio.finalizeGObject)
    result.impl = gobj
    GC_ref(result)
    if g_object_is_floating(result.impl).int != 0:
      discard g_object_ref_sink(result.impl)
    g_object_add_toggle_ref(result.impl, toggleNotify, addr(result[]))
    g_object_unref(result.impl)
    assert(g_object_get_qdata(result.impl, Quark) == nil)
    g_object_set_qdata(result.impl, Quark, addr(result[]))

```

>  I am a bit surprised that this happened for GTK3, which is regarded as stable now.

I'm surprised too, and realized that I downgraded the wrong package. I should have downgrade glib.
The glib update was a minor update, so it makes sense that it's broken now:
```
[2021-09-28T18:32:44+0200] [ALPM] upgraded glib2 (2.68.3-1 -> 2.70.0-1)
```
>  For my Linux box there is currently only g_memory_monitor_dup_default(), but you should have one more.

I still only have one `g_memory_monitor_dup_default()` function:

```
[dankrad@TNB gintro-0.9.4]$ grep -A2 "proc g_memory_monitor_dup_default" ~/.nimble/pkgs/gintro-0.9.4/gintro/gio.nim 
proc g_memory_monitor_dup_default(): ptr MemoryMonitor00 {.
    importc, libprag.}

```

**Comment by StefanSalewski** [comment]
Should be fixed in #head.

Please try with

```
nimble uninstall gintro
nimble install gintro@#head
```

I have done a manually rename of the procs:

```
< fixedProcNames["g_memory_monitor_dup_default"] = "dupDefaultMemoryMonitor"
< fixedProcNames["g_power_profile_monitor_dup_default"] = "dupDefaultPowerProfileMonitor"
```

We could consider trying to detect such name conflicts automatically, and do a plain automatic rename in that cases appending a number to the proc name.

On the other hand, I think this is the first time in 5 years that we got surprised by such a NEW name conflict. Indeed as it was glib/gio that changes are not that surprising, they still develop GTK4, and GTK3 and GTK4 uses the same glib. Indeed I just updated my Gentoo Linux box and got the same name conflict -- there must have been a Gentoo update in the last few days, as a week ago all was still fine.

When it works for you, I will then ship v0.9.5 in the next days.

**Comment by Dankr4d** [comment]
This issue is fixed in my case. Thank you!
