### ISSUE TITLE
"accelMods" and "accelFlags" should be sets

### ISSUE THREAD

**Issue by lscrd** [StefanSalewski/gintro#19]
The procedure "addAccelerator" for "Widget" accepts a parameter "accelMods" which is of type "gdk.ModifierType" and a parameter "accelFlags" which is of type "AccelFlags". Both types are enums. I think that, in either case, these parameters should be a set of these enum values.

**Comment by StefanSalewski** [comment]
Both needs special care:

modifierMask = 1543512063 # that is not a power o 2

mask = 7 # same

Because of this automatic conversion to set of enum is not performed. gdk.ModifierType may even need renaming of entries, as name mask is bad for single bits. And after renaming it needs some documentation too. I did a similar special handling for EventMask already. Providing a special proc or code it manually both is some carefully work, so I will delay it for now...

**Comment by lscrd** [comment]
Yes, you are right. A set would seem a good solution, but it needs bit ranks, not values and if a value is not a power of two, it becomes complicated.

But, for now, how can I combine *shiftMask* and *controlMask* for instance? Of course, I can write `ord(shiftMask) or ord(controlMask)`, but this is not of the right type and casting to *modifierType* would be an error as this is not a legal value for this enum. However, this may work if there is no runtime check.

A way to solve the difficulty would be to considerer that ModifierType is itself a set of enums (not illogical as there are indeed masks). So, we would define the constants as sets to combine using "+". And we would have something like that:

```Nim
shiftMask = {0}
lockMask = {1}
controlMask = {3}
.......
modifierMask = {0..12, 26..28, 30}
```

Combining *shiftMask* and *controlMask* would then be done using `shiftMask + controlMask`.

Of course, if we want to keep the Gtk3 values, we have to resort to a special proc as you said.

**Comment by StefanSalewski** [comment]
Fixed by using the existing proc which was used for EventMask already. AccelFlagsMask with numerical value 7 is not provided currently, the problem was that the mask covers more than what the individual bits occupy, so we can not define that mask as a set of individual bits. We may use an ugly cast or we have to add dummy bits. I have the feeling that that mask is never used by applications. When we find a use case for it we will add it.

All that bits and masks are untested yet!

**Comment by lscrd** [comment]
I have changed my program to use this new interface and it works. I have not checked all the values, but for *ModifierFlag*, *control* is OK and and *control + shift* is OK. For the *AccelFlag*, I have only used the *visible* flag. Thanks!
