### ISSUE TITLE
could not load: libgtk-4.so.1

### ISSUE THREAD

**Issue by gavr123456789** [StefanSalewski/gintro#192]
Today I updated all packages(with GTK I think), and now I get this error, when trying to run my [Dela](https://github.com/gavr123456789/Dela) GTK 4 app.   
Got this just after `nimbe build` and `./TaskManager`.  
Now I will try to reinstall gintro to check will it fix the problem.

**Comment by StefanSalewski** [comment]
Generally, after updating gtk related libraries, it can be necessary to reinstall gintro.

**Comment by gavr123456789** [comment]
I cant install gintro now:  
```
First we try generating bindings for GTK4, this may fail when GTK4 is not properly installed
on your computer. But don't worry, you can still use GTK3
Can't load gtk4 library!

** (process:25270): WARNING **: 16:50:55.968: Failed to load shared library 'libgtk-4.so.1' referenced by the typelib: /usr/lib/libgtk-4.so.1: undefined symbol: pango_attr_word_new
/tmp/gintrosalewski/gen.nim(4462) gen
```

**Comment by StefanSalewski** [comment]
That is really strange, there should be no hard-coded version number.

I will update GTK4 from git sources in the next days and try myself. Unfortunately you seems to be the only gintro user currently, so we do not know if it is only a problem of your Arch-Linux OS.

Have you done an "nimble uninstall gintro" before? I always do that, but don't know if it is necessary.

**Comment by StefanSalewski** [comment]
Line 4462 in gen.nim seems to be related to libnotify. But I have no idea for the reason. I may try to install libnotify from git sources soon. But currently I have still to do some other work, sorry.

**Comment by gavr123456789** [comment]
No, Im not the only gintro user, the others on not rolling distros, I know another 2-3 who asked me questions in telegram.

**Comment by gavr123456789** [comment]
> Have you done an "nimble uninstall gintro" before? I always do that, but don't know if it is necessary.   
  
Ye, same

**Comment by zhenyamega** [comment]
> Unfortunately you seems to be the only gintro user currently, so we do not know if it is only a problem of your Arch-Linux OS.

![fcfs](https://user-images.githubusercontent.com/22717765/147952920-780350fc-f91a-4a82-aecc-e7306f56273a.gif)

**Comment by StefanSalewski** [comment]
zhenyamega, please do not pollute this issue tracker with your videos. We have to do some serious discussions here to solve real problems. You may upload your videos to youtube or show it your mon.

gavr, I have really no idea, and no hope that I may be able to reproduce your issue. It is really strange, we never had something like that in the last five years. Do other gtk4 programs work for you? Have you also updated the Nim compiler or gcc? Maybe the only solution would be, that I buy one more box and install your arch linux as well? But unfortunately I am really busy for the next 6 months, and I would really like to finish the Nim book this year. Some years ago I had some hope that we may hire some smart Rust and GTK devs and request a rewrite of the Nim Gtk bindings, but due to the few users of GTK and Nim now that is not an realistic option any more :-(

Does C and Vala still work for you? In the GTK4 book there should be a C example program, can you still compile and run that one?

**Comment by gavr123456789** [comment]
Huuh, it turns out I really haven't tried running gtk 4 programs, gtk 4-demo isn't starting for me right now, other gtk 4 programs that I tried were installed via flatpak, sorry for wasted time.

**Comment by gavr123456789** [comment]
The thing was that for some reason pango was built from git, instead of an officially installed package, it provided the same dependency for gtk, so everything was going, but could not start, because of some new method `pango_attr_word_new` inside

**Comment by StefanSalewski** [comment]
Fine that you have been able to fix your issue. Unfortunately the error message was not really helpful.
