### ISSUE TITLE
Button connects doesn't work with latest gintro version

### ISSUE THREAD

**Issue by dmknght** [StefanSalewski/gintro#202]
Gintro: `gintro-#head`
GTK: `3.24.24-4+deb11u2`

Problem: Program failed to compile. It worked perfectly with version 0.9.6. Error logs
```
stack trace: (most recent call last)
gimplgobj.nim(99, 13)    mconnect
/home/dmknght/ParrotProjects/anonsurf/nimsrc/anonsurf/AnonSurfGTK.nim(45, 13) template/generic instantiation of `connect` from here
/home/dmknght/.nimble/pkgs/gintro-#head/gintro/gimplgobj.nim(99, 13) Error: node is not a symbol
make: *** [Makefile:36: build] Error 1
```

A part of my code
```
let btnRestart = newButton("Restart")
btnRestart.connect("clicked", ansurf_gtk_do_restart, cb_send_msg)
```
`cb_send_msg` is a callback function. I guess macro failed to pass a function via argv.

**Comment by StefanSalewski** [comment]
Did a test with

```
nimble install https://github.com/dmknght/anonsurf.git
Downloading https://github.com/dmknght/anonsurf.git using git
  Verifying dependencies for AnonSurfGUI@0.1.0
 Installing AnonSurfGUI@0.1.0
   Building AnonSurfGUI/AnonSurfGUI using c backend
/tmp/nimble_33554/githubcom_dmknghtanonsurfgit/src/AnonSurfGUI.nim(1, 15) Error: cannot open file: gintro/gtk
       Tip: 2 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: AnonSurfGUI
        ... Execution failed with exit code 1
        ... Command: /home/salewski/Nim/bin/nim c --colors:on --noNimblePath -d:release -d:NimblePkgVersion=0.1.0 --hints:off -o:/tmp/nimble_33554/githubcom_dmknghtanonsurfgit/AnonSurfGUI /tmp/nimble_33554/githubcom_dmknghtanonsurfgit/src/AnonSurfGUI.nim
```

Will investigate later or tomorrow.

**Comment by StefanSalewski** [comment]
>proc ansurf_gtk_do_restart*(b: Button, cb_send_msg: proc)

I did not even know that passing a proc as optional parameter to the connect() macro was possible. It was never intended and never tested. That it refuse to work since v0.9.7 is related with our patches for Mr. Avr. I always said that the patches are ugly, only to support tuples, which could be replaced by ref objects just fine. But well, now we have the tuple code in gintro for more than six months. The ugly part is, that we have to handle each data type of the optional parameters now separately. So we have to see how we can handle a proc data type. But we should really rewrite the connect macro to use pure AST manipulation. I am not really good in writing macros, maybe more than a week for me, when I manage it at all. And I try to concentrate on the Nim book, I would like to finish it before Nim looses all its users. But I will try one more ugly patch to get your code working again. I really wonder that it was working with v0.9.6 -- I have no idea what a proc data type really is, and how passing a Nim proc to C functions may work. And the calling convention, cdecl and such, may also be a problem. I was really surprised that tuples have worked, but that procs have worked is magic.

**Comment by dmknght** [comment]
Oh the passing proc was working with 0.8.0 as well. And i believe passing callback is normal in C lang? I don't know anything about Macro so i just did a quick check and I saw mconnect is totally different. That's all LoL.
I added a line like this
![image](https://user-images.githubusercontent.com/29118926/162043098-cb28e79a-8d8b-4d2c-a484-9af9724c18f4.png)

Assume the last kind is when program failed to build, the `at.kind` showed type `nnkProcTy`
![image](https://user-images.githubusercontent.com/29118926/162043160-bcc02553-6092-48e7-ac23-5df27afa63b5.png)

So i guess, at least it could be a dirty way to check and handle it in macro

**Comment by StefanSalewski** [comment]
I have just looked at some of your code, and I have to admit that I do understand not much. You do even create new threads, to which you pass that proc. Really interesting that all that has been working. I think I have never used proc parameters in pure Nim code before, and I still have to learn how Nim ensures matching parameter lists. Seems that we can assign to a proc variable procedures with different parameter lists. But then, when we later call that proc, how does Nim ensures that all parameters are correct. In C this is a problem.

But I think I do not have to understand all that to fix your issue, what I have to know is if I have to call GC_ref() on the proc to avoid destroying it by the GC. Will see.

**Comment by dmknght** [comment]
> You do even create new threads, to which you pass that proc.

Oh that was something I asked here long time ago about GUI not responding when use thread (the refesh GUI and time wait). I used procs because the logic when click on some buttons is the same, and I want to do the logic for both GUI and CLI, so I used call back procs that handle either echoing in CLI or showing system's notification. 

> I still have to learn how Nim ensures matching parameter lists

I think I had similar issue before but i managed to made it work and I can't remember LoL.

> But I think I do not have to understand all that to fix your issue

That's great! If you need to test the code, I'm available to help :D

**Comment by dmknght** [comment]
> Maybe this plain fix will do:
> 
> ```
> diff ~/.nimble/pkgs/gintro-#head/gintro/gimplgobj.nim gimplgobj.nim 
> 96,99d95
> < 
> <   elif at.kind == nnkProcTy: # v0.9.8
> <     ats = at.toStrLit.strVal
> ```
> 
> Please try with
> 
> nimble install gintro@#head

Thank you it worked perfectly. I'm closing this issue now. Thanks a lot <3
