### ISSUE TITLE
wrong argument in proc `getData` and `data` from `gstbase.nim`

### ISSUE THREAD

**Issue by piertoni** [StefanSalewski/gintro#220]
On `gstbase.nim` i have the following procs:

```
proc getData*(self: BitWriter): seq[uint8] =
  result = uint8ArrayToSeq(gst_bit_writer_get_data(cast[ptr BitWriter00](self.impl)), .int)

proc data*(self: BitWriter): seq[uint8] =
  result = uint8ArrayToSeq(gst_bit_writer_get_data(cast[ptr BitWriter00](self.impl)), .int
```
As you can see the final `.int` is wrong.
This should be replaced with `self.size` but to make it work also the declaration of `proc size` that is some lines after this should be moved up.
As this is autogenerated I don't know how to make eventually the modification in the source code.

**Comment by StefanSalewski** [comment]
Thanks for reporting, I will investigate that issue soon.

**Comment by StefanSalewski** [comment]
I just tried to fix it. The reason for the issue was, that the bindings generator assumed a second argument in the function call, which receives the array length. Some GTK functions use that, but gst is special. I think that your guess is correct, that some form of self.size may give the actual length. But for the bindings generator, that seems to be impossible to guess. So I think that we have to create that function manually. So my patch is

```
diff ~/gintrotest/test/gen.nim gen.nim 
3c3
< # v 0.9.9 2023-APR-07
---
> # v 0.9.9 2023-JAN-31
461,462d460
< #mangledTypes["ptr HarnessPrivate00"] = "pointer"
< 
2022,2024d2019
<   if sym == "gst_bit_writer_get_data": return # no chance for automatic generation, so we have to do it manually
< 
< 
3624,3634d3618
< const GstBase_EPI = """
< 
< # GstBase_EPI
< proc gst_bit_writer_get_data(self: ptr BitWriter00): ptr uint8 {.
<     importc, libprag.}
< 
< proc getData*(self: BitWriter): seq[uint8] =
<   result = uint8ArrayToSeq(gst_bit_writer_get_data(cast[ptr BitWriter00](self.impl)), gst_bit_writer_get_size(self.impl).int)
< 
< """
< 
3934,3936d3917
<   elif namespace == "GstCheck":
<     output.writeLine("type\n  HarnessPrivate00 = object")
< 
4419,4421d4399
<   if namespace == "GstBase":
<     output.write(GstBase_EPI)
< 
4711c4689
< # 4711 lines
---
> # 4687 lines
```

I have also added a dummy HarnessPrivate00 type for gstcheck, to make that module compile. I am not able to actually test the getData() proc, but at least the module compiles now.

Generally I hope, that you do not really intend to use the Nim GST bindings. GStreamer is an extremely low level library, so all bindings have a very hard time. I added gstreamer to gintro long time ago, because some people asked for it. But it was a bad decision, that module is too complicated and low level. When you still intend to try it, then you can always make fixes direct in the modules like  ~/.nimble/pkgs2/gintro-0.9.9-d2be110997211a820389624eaca4b30c27f25b85/gintro/*.gst. That is how I generally test fixes first, before I modify the gen.nim generator script for it.

**Comment by piertoni** [comment]
Thanks for your time and fixes, generally speaking, as you do not suggest to use gintro for gstreamer what is your suggestion? Create my own repository specific for gstreamer? Or contribute in some other ways?

**Comment by StefanSalewski** [comment]
When you really need gstreamer, I would just use plain C. GStreamer is a very low level lib, so putting some high level bindings on top of it makes it not really better. Do you really need GStreamer? Maybe Rust is an option when you do not like C, you may ask Mr. Droege about the state of Rust GStreamer support. But I have not seen him for a long time in the Gnome forum. Are there at all still people using GStreamer for new projects? I look from time to time into the Gnome forum, and can not really remember projects. And I think, that generally very few people create new software with GTK in these days, I think I have seen none in the last decade in gnome forum or on github.

But of course it is possible for you to use GStreamer with gintro. When you know GStreamer well, it is easy to discover bug in the auto-generated bindings and replace them with manually ones. For me, I know nothing about GStreamer, so testing and fixing all bugs would be a giant amount of work. For the other GTK core bindings the situation is much better, I assume only very few bugs. One issue is, that we can currently not create new gobjects with new properties, adding that would be some work. But as you may have noticed, only very few people are still using gintro at all, I guess 2 or three including myself.

Another option for you with Nim and gstreamer would be to use the low level futhark bindings of Mr. Munch. I recently had a conversation with Mr. Munch, and he said that this futhark works not bad. The disadvantage of futhark bindings is, that they are fully low level, you use pointers, addr() and have to free memory manually. For other GTK libs that is a pain, I did it for my NEd editor with the oldgtk3 bindings in 2017. For GStreamer, it may be OK.

**Comment by piertoni** [comment]
What alternatives exists to Gstreamer? Not many... ffmpeg probably?
I think that in this sense bindings to Gstreamer are less likely to become obsolete than GTK and probably this could be the reason that the module is so different as is evolving faster.
Anyway thanks for your effort!

**Comment by StefanSalewski** [comment]
Sorry for late reply, I was very busy. I can not really help you, but when you are basically interested in gstreamer with Nim, you may contact P. Munch with his https://github.com/PMunch/futhark, that may be a good solution.
