### ISSUE TITLE
issues when multiple versions of a package are installed

### ISSUE THREAD

**Issue by barcharcraz** [StefanSalewski/gintro#30]
I've got both Gtk-3.0 and Gtk-4.0 installed on my machine, and by default gintro will only generate nim code for Gtk-4.0!. I think this is because the generator never unloads namespaces, so if there are two separate version only the first one loaded gets generated

**Comment by StefanSalewski** [comment]
That is interesting, thanks for reporting.

I can not test it currently, as my Gentoo box has only GTK3 available. But I will see if there is an promising way to fix it.

With latest Nim devel and upcomming  Nim v0.19 (1.0 candidate) we should get some more trouble, as Nim strings are not pointers any more, but many GTK functions likes to accept NULL string pointers. And maybe we should replace the finalizers by destructors.

But I think currently no one is using Nim GTK seriously, so maybe we better wait until official GTK4 and NIM 1.0 or 2.0 is out.

**Comment by barcharcraz** [comment]
Nim is a great candidate to do what vala currently does if we can get the gtk support going.

**Comment by StefanSalewski** [comment]
I have done the fixes to make it work with latest Nim devel again, so it may work for upcomming v0.19.

Your problem with GTK4 is not really easy to fix -- I asked yesterday on GTK mailing list, but got not yet a response, and I have not much hope for one :-)

Currently I am using NULL for the version string, which gives me the latest version for all GTK related libs. I have no idea if something like "<4.0" would work for version string, I can not test because for my Gentoo box there is no official GTK4 available currently. And I would not like to break it for other people who just wants latest GTK3 libs.

Indeed I have no idea how you manage to install GTK3 and GTK4 at the same time, as GTK4 seems to call itself something like v3.90x so it may replace real GTK3 when installed.

**Comment by StefanSalewski** [comment]
gintro should support GTK3/GTK4 now, so I will close this issue. Please reopen if there are still problems.
